import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    My navbar
                    <ul>
                        <li>
                            <Link href="/">Home</Link>
                            <Link href="/about">About</Link>
                        </li>
                    </ul>
                </nav>
                <main className={styles.main}>{children}</main>
            </body>
        </html>
    );
}
